"""Claude Code hook adapter.

Reads a Claude Code PreToolUse JSON payload from sys.stdin, rewrites the
`tool_input.command` field if Quor has a rewrite for it, and writes a
`hookSpecificOutput.updatedInput` response to sys.stdout — the only shape
Claude Code actually honors for overriding tool arguments
(see https://code.claude.com/docs/en/hooks.md). `updatedInput` is omitted
when no rewrite applies, so Claude Code executes the original command.

Called by __main__._run_hook() which guarantees:
- sys.stdin is a TextIOWrapper over the original stdin bytes
- Any exception raised here is caught by __main__ and returns original bytes
"""

from __future__ import annotations

import sys
from typing import Any

import orjson

from quor.adapters.base import HookInput
from quor.rewrite.classifier import rewrite_command

# ---------------------------------------------------------------------------
# Hook script template — written by `quor init --claude` (Phase 7)
# Placeholders: {python} is replaced with sys.executable at install time.
# ---------------------------------------------------------------------------

HOOK_COMMAND = "{python} -m quor hook claude"

HOOK_PS1_TEMPLATE = """\
# Quor hook script — generated by `quor init --claude`
# quor-hook-schema: {schema_version}
# Do not edit this file. To update, run `quor init --claude` again.
$ErrorActionPreference = 'Stop'
$json = [Console]::In.ReadToEnd()
$json | & '{python}' -m quor hook claude
"""

_UTF8_BOM = "﻿"


def run_hook() -> None:
    """Process one PreToolUse hook call.

    Reads JSON from sys.stdin (already set up by __main__._run_hook).
    Writes a `hookSpecificOutput` response to sys.stdout.
    Raises on parse/validation errors — caller handles fail-open.
    """
    raw = sys.stdin.read()

    # Strip UTF-8 BOM (single or doubled — Cursor sends doubled BOM on Windows)
    raw = raw.lstrip(_UTF8_BOM)

    # Parse full payload as a dict so extra tool_input fields are preserved
    data: dict[str, Any] = orjson.loads(raw)

    # Validate the fields we care about (raises ValidationError on bad shape)
    hook_input = HookInput.model_validate(data)
    original_cmd = hook_input.tool_input.command

    hook_specific: dict[str, Any] = {
        "hookEventName": "PreToolUse",
        "permissionDecision": "allow",
    }

    rewritten = rewrite_command(original_cmd)
    if rewritten is not None and rewritten != original_cmd:
        # Preserve sibling tool_input fields (e.g. "description") — updatedInput
        # replaces the whole tool_input object, not just the command field.
        updated_input = dict(data.get("tool_input", {}))
        updated_input["command"] = rewritten
        hook_specific["updatedInput"] = updated_input

    sys.stdout.buffer.write(orjson.dumps({"hookSpecificOutput": hook_specific}))
    sys.stdout.buffer.flush()
