"""Claude Code hook adapter.

Reads a Claude Code PreToolUse JSON payload from sys.stdin, rewrites the
`tool_input.command` field if Quor has a filter for it, and writes the
(possibly modified) JSON to sys.stdout.

Called by __main__._run_hook() which guarantees:
- sys.stdin is a TextIOWrapper over the original stdin bytes
- Any exception raised here is caught by __main__ and returns original bytes
"""

from __future__ import annotations

import sys
from typing import Any

import orjson

from quor.adapters.base import HookInput
from quor.rewrite.classifier import rewrite_command

# ---------------------------------------------------------------------------
# Hook script template — written by `quor init --claude` (Phase 7)
# Placeholders: {python} is replaced with sys.executable at install time.
# ---------------------------------------------------------------------------

HOOK_COMMAND = "{python} -m quor hook claude"

HOOK_PS1_TEMPLATE = """\
# Quor hook script — generated by `quor init --claude`
# Do not edit this file. To update, run `quor init --claude` again.
$ErrorActionPreference = 'Stop'
$json = [Console]::In.ReadToEnd()
$json | & '{python}' -m quor hook claude
"""

_UTF8_BOM = "﻿"


def run_hook() -> None:
    """Process one PreToolUse hook call.

    Reads JSON from sys.stdin (already set up by __main__._run_hook).
    Writes modified JSON to sys.stdout.
    Raises on parse/validation errors — caller handles fail-open.
    """
    raw = sys.stdin.read()

    # Strip UTF-8 BOM (single or doubled — Cursor sends doubled BOM on Windows)
    raw = raw.lstrip(_UTF8_BOM)

    # Parse full payload as a dict so extra fields are preserved verbatim
    data: dict[str, Any] = orjson.loads(raw)

    # Validate the fields we care about (raises ValidationError on bad shape)
    hook_input = HookInput.model_validate(data)
    original_cmd = hook_input.tool_input.command

    rewritten = rewrite_command(original_cmd)
    if rewritten is not None and rewritten != original_cmd:
        # Modify the dict in-place to preserve every extra field
        data["tool_input"]["command"] = rewritten

    sys.stdout.buffer.write(orjson.dumps(data))
    sys.stdout.buffer.flush()
