"""Claude Code PostToolUse/Read hook adapter.

Reads a Claude Code PostToolUse JSON payload from sys.stdin, routes the
Read tool's file path through the existing `FilterRegistry` (QB-007C) —
exactly the same registry/`Pipeline` machinery `quor/adapters/dispatcher.py`
already uses for Bash output, just matched against a file path instead of a
command string (see `quor/filters/builtin/markdown.toml`'s header comment
for why that reuse is safe). If a filter matches and actually changes the
content, the compressed result is returned via `updatedToolOutput`; in
every other case (no filter match, compression is a no-op, or anything
raises) `updatedToolOutput` is omitted and Claude Code keeps the original
Read result — the same "omit the key rather than emit an empty/wrong value"
discipline ADR-030 established for `updatedInput`.

`.md`/`.markdown`/`.txt`/`.rst` files compress directly (QB-007B's
`markdown`/`document-text` filters), matched by file path exactly as before.
This is enforced by an explicit filter-name allowlist
(`_READ_SUPPORTED_FILTER_NAMES`), not by the absence of a `FilterRegistry`
match: the Bash-oriented `generic` filter matches literally every non-empty
string (including any file path), so without the allowlist an unsupported
file would be silently routed through a shell-output filter never designed
for document content. See that constant's own comment for the full
rationale.

`.docx`/`.pdf` files (QB-007E4) take a second path: the binary document is
first converted to Markdown-shaped text by `quor/pipeline/extract`
(QB-007E1/E2/E3, reused here completely unchanged — see
`_compress_extracted_document`'s own docstring), and *that* text is then run
through the exact same `markdown` `FilterConfig` the `.md` path already
uses — looked up by name via `FilterRegistry.all_filters()`, not by a new
`docx.toml`/`pdf.toml` file path pattern, so there is still only one
Markdown-compression filter in the entire system.

`.py`/`.js`/`.jsx`/`.mjs`/`.cjs`/`.ts`/`.tsx` files (QB-005F) take a third
path, for the same structural reason as `.docx`/`.pdf`: the `cat-python`/
`cat-javascript`/`cat-typescript`/`cat-tsx` filters (QB-005B-D) already exist
and already wrap the AST-summarization pipeline, but their `match_command`
patterns are all shaped like `^cat\\s+...\\.py\\b` — a literal `cat `-prefixed
command string a bare Read `file_path` (e.g. `"src/app.py"`) can never
match. So, exactly like the extracted-document path, the matching filter is
looked up **by name** (`_SOURCE_CODE_FILTER_NAMES_BY_EXTENSION`, keyed by
extension) instead of by `FilterRegistry.find(file_path)`. Unlike the
document path there is no extraction step — the Read `tool_response` is
already the plain source text — so both the content to filter and the
content to compare against are the same `tool_response` value. Both this
path and the document path share their post-lookup "apply, track, omit if
unchanged" tail via `_compress_via_named_filter()`, added in QB-005F when
this exact duplication was identified between the two by-name paths.
Everything else (unsupported extensions, no extension, an extraction
failure, a missing AST dependency, a parse/filter failure, ...) still passes
through unchanged, exactly as before QB-005F.

Called by __main__._run_hook() (adapter name "claude-read"), which
guarantees:
- sys.stdin is a TextIOWrapper over the original stdin bytes
- Any exception raised here is caught by __main__ and returns original bytes
  (a second, outermost fail-open layer on top of the one in
  `_compress_read_output` below)
- A TrackingDB is constructed and passed in as `tracking` (QB-007D), exactly
  as `__main__._run_dispatch()` already does for the Bash path — see
  `_compress_read_output`'s own docstring for what gets recorded and when.
"""

from __future__ import annotations

import sys
import time
import warnings
from pathlib import Path
from typing import Any

import orjson

from quor.adapters.base import PostToolUseHookInput
from quor.config.model import FilterConfig
from quor.filters.registry import FilterRegistry
from quor.pipeline.extract.registry import extract
from quor.tracking.db import TrackingDB, track_invocation

# ---------------------------------------------------------------------------
# Hook script template — written by `quor init --claude` (QB-007A)
# Placeholders: {python} is replaced with sys.executable at install time.
# ---------------------------------------------------------------------------

HOOK_READ_COMMAND = "{python} -m quor hook claude-read"

HOOK_READ_PS1_TEMPLATE = """\
# Quor PostToolUse/Read hook script — generated by `quor init --claude`
# Do not edit this file. To update, run `quor init --claude` again.
$ErrorActionPreference = 'Stop'
$json = [Console]::In.ReadToEnd()
$json | & '{python}' -m quor hook claude-read
"""

_UTF8_BOM = "﻿"

# Explicit allowlist of filter names this adapter will actually apply.
#
# FilterRegistry is shared with the Bash path, whose built-in `generic`
# filter (quor/filters/builtin/z_generic.toml) matches every non-empty
# string via `match_command = '.'` — including a bare Read file path like
# "report.docx" or "script.py", since FilterRegistry has no concept of
# "this string is a file path, not a command". Without this allowlist,
# every unsupported file type would silently be routed to `generic`'s
# ANSI-strip/dedupe/max_tokens(1000, tail) pipeline — a shell-output filter
# never designed for, or tested against, arbitrary document content, and
# exactly the kind of accidental scope expansion QB-007C's requirements
# explicitly rule out ("unsupported file types pass through unchanged").
# Extend this set (not FilterRegistry itself) if a future format needs its
# own dedicated filter — QB-007E4's DOCX/PDF integration deliberately does
# NOT add to this set; extracted DOCX/PDF text is routed to the existing
# "markdown" entry by name (see _MARKDOWN_FILTER_NAME), not matched as a
# file path, so it never needs its own filter-name allowlist entry.
_READ_SUPPORTED_FILTER_NAMES: frozenset[str] = frozenset({"markdown", "document-text"})

# Extensions routed through quor/pipeline/extract (QB-007E1/E2/E3) before
# filtering — the mirror of _READ_SUPPORTED_FILTER_NAMES above, but for the
# extraction path rather than the direct file-path-match path. Kept here
# (not read from quor.pipeline.extract.registry's own routing table) for
# the same reason _READ_SUPPORTED_FILTER_NAMES is adapter-local rather than
# derived from FilterRegistry: this adapter decides what it will *attempt*,
# independent of what the lower layer happens to support today.
_EXTRACTION_EXTENSIONS: frozenset[str] = frozenset({".docx", ".pdf"})

# The one filter extracted DOCX/PDF Markdown-shaped text is compressed
# with — the existing "markdown" FilterConfig (quor/filters/builtin/
# markdown.toml), looked up by name via FilterRegistry.all_filters(), not
# matched against a file path the way the direct .md/.txt path is. No
# docx.toml/pdf.toml exists or is created — see module docstring.
_MARKDOWN_FILTER_NAME = "markdown"

# Extension -> builtin filter name, for source-code Read files (QB-005F).
# Mirrors _MARKDOWN_FILTER_NAME's by-name lookup, not _READ_SUPPORTED_FILTER_NAMES'
# path-match lookup — see module docstring for why: cat-python.toml/
# cat-javascript.toml/cat-typescript.toml's `match_command` patterns all
# require a literal "cat "-prefixed command string, which a bare Read
# file_path can never match via FilterRegistry.find(). Each of these filters
# already exists (QB-005B/C/D) and already wraps the AST-summarization
# pipeline (code_ast_summarize/python_ast_summarize stages) — this mapping
# only makes them *reachable* from the Read hook; no new filter is added
# here. ".jsx"/".mjs"/".cjs" all share cat-javascript, exactly as that
# filter's own match_command already treats them as one language for the
# Bash path.
_SOURCE_CODE_FILTER_NAMES_BY_EXTENSION: dict[str, str] = {
    ".py": "cat-python",
    ".js": "cat-javascript",
    ".jsx": "cat-javascript",
    ".mjs": "cat-javascript",
    ".cjs": "cat-javascript",
    ".ts": "cat-typescript",
    ".tsx": "cat-tsx",
}


def run_hook(*, tracking: TrackingDB | None = None) -> None:
    """Process one PostToolUse/Read hook call.

    Reads JSON from sys.stdin (already set up by __main__._run_hook).
    Writes a `hookSpecificOutput` response to sys.stdout.
    Raises on parse/validation errors — caller (__main__) handles fail-open
    for those; content-routing/compression failures are handled locally by
    `_compress_read_output`, which never raises.

    `tracking` is optional (defaults to None, a no-op) so existing callers
    that don't care about tracking — direct unit tests, in particular — are
    unaffected; `__main__._run_hook()` passes a real `TrackingDB` in
    production, exactly as `_run_dispatch()` already does for Bash.
    """
    raw = sys.stdin.read()

    # Strip UTF-8 BOM (single or doubled — Cursor sends doubled BOM on Windows),
    # same as quor/adapters/claude.py.
    raw = raw.lstrip(_UTF8_BOM)

    data: dict[str, Any] = orjson.loads(raw)

    # Validate the fields we care about (raises ValidationError on bad shape).
    hook_input = PostToolUseHookInput.model_validate(data)

    hook_specific: dict[str, Any] = {"hookEventName": "PostToolUse"}

    compressed = _compress_read_output(hook_input, tracking)
    if compressed is not None:
        hook_specific["updatedToolOutput"] = compressed

    sys.stdout.buffer.write(orjson.dumps({"hookSpecificOutput": hook_specific}))
    sys.stdout.buffer.flush()


def _compress_read_output(
    hook_input: PostToolUseHookInput, tracking: TrackingDB | None
) -> str | None:
    """Return compressed content if (and only if) a filter matched *and*
    actually changed the content; return None in every other case.

    None means "the caller must omit updatedToolOutput" — the single
    fail-open contract this function exists to guarantee, covering:
      - `tool_response` is missing or not a plain string (e.g. a future/
        unknown shape for a binary Read — QB-007B/C are text-only by
        design; see backlog.md's QB-007 entry).
      - `tool_input.file_path` is empty.
      - No filter matches the file path (unsupported extension, or a path
        containing whitespace — see markdown.toml's routing-anchor
        rationale), or a filter matched but isn't one of the document
        filters this adapter is scoped to (see `_READ_SUPPORTED_FILTER_NAMES`)
        — most notably `generic`, which would otherwise catch every
        unsupported file type via its own `match_command = '.'`.
      - The matched filter's rendered output is byte-identical to the
        original (nothing to report — mirrors ADR-030's identical
        "omit if unchanged" rule for the Bash adapter's `updatedInput`).
      - Anything raises — filter registry construction, routing, or
        pipeline execution. Caught here (not just by __main__'s outer
        guard) so a single bad filter can't take down routing for every
        other Read call in the same process; mirrors
        `quor/adapters/dispatcher.py`'s own filter-layer try/except.

    Tracking (QB-007D): every branch that represents a genuine Read
    invocation — i.e. `file_path` is non-empty — calls `track_invocation()`
    exactly once before returning, mirroring how `dispatcher.py` tracks
    every Bash invocation it dispatches. The `command` column gets
    `"Read: {file_path}"` so Read rows are self-describing next to Bash
    rows in the same table; no schema change, no new storage. A `file_path`
    of "" is the one case treated as "nothing happened" and left untracked
    — the same way `dispatcher.run_dispatch([])` returns before dispatching
    or tracking anything for empty `args`.

    The passthrough/filter-name split mirrors `dispatcher.py`'s own
    `_lookup_filter`/`_apply_content_filter` split exactly:
      - no match, or a match outside `_READ_SUPPORTED_FILTER_NAMES`
        (including a `FilterRegistry` construction/lookup error) →
        `filter_name=None, was_passthrough=True` — nothing was applied.
      - a supported filter matched, whether or not applying it changed the
        content or raised (fail-open falls back to the original response) →
        `filter_name=<name>, was_passthrough=False` — a filter was
        genuinely attempted, same as dispatcher tracking `filter_config.name`
        even when `_apply_content_filter` itself caught an error.

    QB-007E4: a `.docx`/`.pdf` file path (`_EXTRACTION_EXTENSIONS`) is
    diverted to `_compress_extracted_document` before any of the above —
    see that function's own docstring for its tracking/fail-open contract,
    which mirrors this one exactly (extraction failure ≈ "no filter
    matched"; a successful extraction ≈ "the markdown filter matched").

    QB-005F: a source-code file path whose extension is a key in
    `_SOURCE_CODE_FILTER_NAMES_BY_EXTENSION` is diverted straight to
    `_compress_via_named_filter` (no extraction step, no separate branch
    function — the shared helper is called directly, since there's nothing
    else this branch needs to do first). Tracking/fail-open contract is the
    same shared helper both this path and `_compress_extracted_document`
    use, so it mirrors both exactly.

    Every other extension keeps using the exact code below, unmodified.
    """
    tool_response = hook_input.tool_response
    file_path = hook_input.tool_input.file_path
    if not file_path:
        return None

    t0 = time.monotonic()
    command = f"Read: {file_path}"

    if not isinstance(tool_response, str):
        track_invocation(
            tracking,
            command=command,
            original="",
            filtered="",
            filter_name=None,
            was_passthrough=True,
            t0=t0,
        )
        return None

    suffix = Path(file_path).suffix.lower()

    if suffix in _EXTRACTION_EXTENSIONS:
        return _compress_extracted_document(
            file_path=file_path,
            tool_response=tool_response,
            tracking=tracking,
            t0=t0,
            command=command,
        )

    source_filter_name = _SOURCE_CODE_FILTER_NAMES_BY_EXTENSION.get(suffix)
    if source_filter_name is not None:
        return _compress_via_named_filter(
            content=tool_response,
            original=tool_response,
            filter_name=source_filter_name,
            tracking=tracking,
            t0=t0,
            command=command,
        )

    try:
        registry = FilterRegistry(project_root=Path.cwd())
        filter_config = registry.find(file_path)
    except Exception as exc:  # noqa: BLE001 — fail-open: never let a filter error surface
        warnings.warn(f"[quor] Read filter error: {exc}", stacklevel=2)
        filter_config = None

    if filter_config is None or filter_config.name not in _READ_SUPPORTED_FILTER_NAMES:
        track_invocation(
            tracking,
            command=command,
            original=tool_response,
            filtered=tool_response,
            filter_name=None,
            was_passthrough=True,
            t0=t0,
        )
        return None

    try:
        rendered = registry.apply(filter_config, tool_response)
    except Exception as exc:  # noqa: BLE001 — fail-open: never let a filter error surface
        warnings.warn(f"[quor] Read filter error: {exc}", stacklevel=2)
        rendered = tool_response

    track_invocation(
        tracking,
        command=command,
        original=tool_response,
        filtered=rendered,
        filter_name=filter_config.name,
        was_passthrough=False,
        t0=t0,
    )

    if rendered == tool_response:
        return None
    return rendered


def _compress_extracted_document(
    *,
    file_path: str,
    tool_response: str,
    tracking: TrackingDB | None,
    t0: float,
    command: str,
) -> str | None:
    """DOCX/PDF branch of `_compress_read_output` (QB-007E4).

    Desired pipeline (per QB-007E4's own spec):
        Read request → claude_read.py → extract(file_path) →
        FilterRegistry ("markdown", by name) → Pipeline → updatedToolOutput

    `quor.pipeline.extract.registry.extract()` is reused completely
    unchanged — it already guarantees fail-open (returns `None`, never
    raises) for a missing dependency, corrupt/encrypted file, or any other
    extraction failure; that `None` is treated exactly like "no filter
    matched" in the non-extraction path above. The `try/except` around the
    call is defense-in-depth (mirroring every other call in this file),
    not a sign that `extract()`'s own contract is doubted.

    Once extraction succeeds, the resulting Markdown-shaped text is run
    through the *existing* `"markdown"` `FilterConfig`
    (`quor/filters/builtin/markdown.toml`) via `_compress_via_named_filter`
    — looked up by name via `FilterRegistry.all_filters()`, not matched
    against `file_path` (which is still `"report.docx"`, not something
    `markdown.toml`'s `^\\S+\\.(md|markdown)$` pattern would ever match). No
    new filter file, no new routing system, no new stage —
    `FilterRegistry.apply()` is called exactly as it already is everywhere
    else.

    Tracking mirrors `_compress_read_output`'s own contract precisely:
      - extraction returns `None` → `filter_name=None, was_passthrough=True`
        — nothing was applied, same as "no filter matched" above.
      - extraction succeeds → delegated to `_compress_via_named_filter`,
        which tracks `filter_name="markdown", was_passthrough=False`
        whether or not the markdown filter changes the result, or even if
        applying it fails and falls back to the unfiltered extracted text —
        a filter was genuinely attempted, same as the non-extraction path
        tracks `filter_config.name` even when `_apply_content_filter`-
        equivalent handling caught an error.
      - `original_tokens` is always derived from the *original*
        `tool_response` (the raw Read result before extraction, passed as
        `_compress_via_named_filter`'s `original`), and `final_tokens` from
        whatever is actually returned as `updatedToolOutput` (or, on a
        filter failure, the unfiltered extracted text that was actually
        returned) — `track_invocation()` computes both via `count_tokens()`
        exactly as it already does for every other producer.

    Returns `None` (omit `updatedToolOutput`) if extraction failed, or if
    the final result happens to equal the original `tool_response` byte
    for byte (mirrors ADR-030's "omit if unchanged" rule) — never raises.
    """
    try:
        extracted = extract(Path(file_path))
    except Exception as exc:  # noqa: BLE001 — fail-open: extraction must never surface here
        warnings.warn(f"[quor] Read extraction error: {exc}", stacklevel=2)
        extracted = None

    if extracted is None:
        track_invocation(
            tracking,
            command=command,
            original=tool_response,
            filtered=tool_response,
            filter_name=None,
            was_passthrough=True,
            t0=t0,
        )
        return None

    return _compress_via_named_filter(
        content=extracted,
        original=tool_response,
        filter_name=_MARKDOWN_FILTER_NAME,
        tracking=tracking,
        t0=t0,
        command=command,
    )


def _compress_via_named_filter(
    *,
    content: str,
    original: str,
    filter_name: str,
    tracking: TrackingDB | None,
    t0: float,
    command: str,
) -> str | None:
    """Look up `filter_name` by name (not by `FilterRegistry.find()`'s
    command/path-pattern match), apply it to `content`, track the
    invocation, and return the rendered result — or `None` if it's
    unchanged from `original`. Never raises.

    Extracted in QB-005F from `_compress_extracted_document`'s own
    post-extraction tail, once the source-code Read path (below) needed the
    identical "by-name lookup -> apply -> track -> omit if unchanged"
    sequence. The only real difference between the two callers is *how*
    `content` was obtained (extracted from a binary document vs. already
    plain source text) — everything after that point was byte-for-byte
    identical duplicated code, so only that shared tail was extracted, not
    a new generic routing/dispatch layer.

    `content` and `original` are deliberately separate parameters because
    they differ for `_compress_extracted_document` (`content` is the
    extracted Markdown text, `original` is the raw pre-extraction
    `tool_response`, so tracking's token-savings numbers stay anchored to
    what Claude actually received from Read) but are the same value for the
    source-code path (there is no extraction step, so both are
    `tool_response`).

    Every failure mode (registry construction, filter lookup, `apply()`)
    falls open to `content` unchanged, exactly like every other filter call
    in this module — a warning is emitted, nothing raises past this
    function.
    """
    try:
        registry = FilterRegistry(project_root=Path.cwd())
        filter_config = _find_filter_by_name(registry, filter_name)
        rendered = registry.apply(filter_config, content) if filter_config is not None else content
    except Exception as exc:  # noqa: BLE001 — fail-open: never let a filter error surface
        warnings.warn(f"[quor] Read filter error: {exc}", stacklevel=2)
        rendered = content

    track_invocation(
        tracking,
        command=command,
        original=original,
        filtered=rendered,
        filter_name=filter_name,
        was_passthrough=False,
        t0=t0,
    )

    if rendered == original:
        return None
    return rendered


def _find_filter_by_name(registry: FilterRegistry, name: str) -> FilterConfig | None:
    """Look up a `FilterConfig` by its `name` field (project > user > builtin
    priority, same as `FilterRegistry.find()`'s own tier order) rather than
    by matching a command/file-path string — `FilterRegistry` has no
    built-in "find by name" method, so this composes it from the existing
    public `all_filters()` rather than adding one. `FilterRegistry` itself
    is not modified."""
    for _tier, filter_config in registry.all_filters():
        if filter_config.name == name:
            return filter_config
    return None
