"""Claude Code PostToolUse/Read hook adapter.

Reads a Claude Code PostToolUse JSON payload from sys.stdin, routes the
Read tool's file path through the existing `FilterRegistry` (QB-007C) —
exactly the same registry/`Pipeline` machinery `quor/adapters/dispatcher.py`
already uses for Bash output, just matched against a file path instead of a
command string (see `quor/filters/builtin/markdown.toml`'s header comment
for why that reuse is safe). If a filter matches and actually changes the
content, the compressed result is returned via `updatedToolOutput`; in
every other case (no filter match, compression is a no-op, or anything
raises) `updatedToolOutput` is omitted and Claude Code keeps the original
Read result — the same "omit the key rather than emit an empty/wrong value"
discipline ADR-030 established for `updatedInput`.

Only `.md`/`.markdown`/`.txt`/`.rst` files actually compress today (QB-007B's
`markdown`/`document-text` filters) — everything else (DOCX, PDF, code
files, no extension, ...) passes through unchanged. This is enforced by an
explicit filter-name allowlist (`_READ_SUPPORTED_FILTER_NAMES`), not by the
absence of a `FilterRegistry` match: the Bash-oriented `generic` filter
matches literally every non-empty string (including any file path), so
without the allowlist an unsupported file would be silently routed through
a shell-output filter never designed for document content. See that
constant's own comment for the full rationale.

Called by __main__._run_hook() (adapter name "claude-read"), which
guarantees:
- sys.stdin is a TextIOWrapper over the original stdin bytes
- Any exception raised here is caught by __main__ and returns original bytes
  (a second, outermost fail-open layer on top of the one in
  `_compress_read_output` below)
- A TrackingDB is constructed and passed in as `tracking` (QB-007D), exactly
  as `__main__._run_dispatch()` already does for the Bash path — see
  `_compress_read_output`'s own docstring for what gets recorded and when.
"""

from __future__ import annotations

import sys
import time
import warnings
from pathlib import Path
from typing import Any

import orjson

from quor.adapters.base import PostToolUseHookInput
from quor.filters.registry import FilterRegistry
from quor.tracking.db import TrackingDB, track_invocation

# ---------------------------------------------------------------------------
# Hook script template — written by `quor init --claude` (QB-007A)
# Placeholders: {python} is replaced with sys.executable at install time.
# ---------------------------------------------------------------------------

HOOK_READ_COMMAND = "{python} -m quor hook claude-read"

HOOK_READ_PS1_TEMPLATE = """\
# Quor PostToolUse/Read hook script — generated by `quor init --claude`
# Do not edit this file. To update, run `quor init --claude` again.
$ErrorActionPreference = 'Stop'
$json = [Console]::In.ReadToEnd()
$json | & '{python}' -m quor hook claude-read
"""

_UTF8_BOM = "﻿"

# Explicit allowlist of filter names this adapter will actually apply.
#
# FilterRegistry is shared with the Bash path, whose built-in `generic`
# filter (quor/filters/builtin/z_generic.toml) matches every non-empty
# string via `match_command = '.'` — including a bare Read file path like
# "report.docx" or "script.py", since FilterRegistry has no concept of
# "this string is a file path, not a command". Without this allowlist,
# every unsupported file type would silently be routed to `generic`'s
# ANSI-strip/dedupe/max_tokens(1000, tail) pipeline — a shell-output filter
# never designed for, or tested against, arbitrary document content, and
# exactly the kind of accidental scope expansion QB-007C's requirements
# explicitly rule out ("unsupported file types pass through unchanged").
# Extend this set (not FilterRegistry itself) when QB-007D/E add DOCX/PDF
# filters.
_READ_SUPPORTED_FILTER_NAMES: frozenset[str] = frozenset({"markdown", "document-text"})


def run_hook(*, tracking: TrackingDB | None = None) -> None:
    """Process one PostToolUse/Read hook call.

    Reads JSON from sys.stdin (already set up by __main__._run_hook).
    Writes a `hookSpecificOutput` response to sys.stdout.
    Raises on parse/validation errors — caller (__main__) handles fail-open
    for those; content-routing/compression failures are handled locally by
    `_compress_read_output`, which never raises.

    `tracking` is optional (defaults to None, a no-op) so existing callers
    that don't care about tracking — direct unit tests, in particular — are
    unaffected; `__main__._run_hook()` passes a real `TrackingDB` in
    production, exactly as `_run_dispatch()` already does for Bash.
    """
    raw = sys.stdin.read()

    # Strip UTF-8 BOM (single or doubled — Cursor sends doubled BOM on Windows),
    # same as quor/adapters/claude.py.
    raw = raw.lstrip(_UTF8_BOM)

    data: dict[str, Any] = orjson.loads(raw)

    # Validate the fields we care about (raises ValidationError on bad shape).
    hook_input = PostToolUseHookInput.model_validate(data)

    hook_specific: dict[str, Any] = {"hookEventName": "PostToolUse"}

    compressed = _compress_read_output(hook_input, tracking)
    if compressed is not None:
        hook_specific["updatedToolOutput"] = compressed

    sys.stdout.buffer.write(orjson.dumps({"hookSpecificOutput": hook_specific}))
    sys.stdout.buffer.flush()


def _compress_read_output(
    hook_input: PostToolUseHookInput, tracking: TrackingDB | None
) -> str | None:
    """Return compressed content if (and only if) a filter matched *and*
    actually changed the content; return None in every other case.

    None means "the caller must omit updatedToolOutput" — the single
    fail-open contract this function exists to guarantee, covering:
      - `tool_response` is missing or not a plain string (e.g. a future/
        unknown shape for a binary Read — QB-007B/C are text-only by
        design; see backlog.md's QB-007 entry).
      - `tool_input.file_path` is empty.
      - No filter matches the file path (unsupported extension, or a path
        containing whitespace — see markdown.toml's routing-anchor
        rationale), or a filter matched but isn't one of the document
        filters this adapter is scoped to (see `_READ_SUPPORTED_FILTER_NAMES`)
        — most notably `generic`, which would otherwise catch every
        unsupported file type via its own `match_command = '.'`.
      - The matched filter's rendered output is byte-identical to the
        original (nothing to report — mirrors ADR-030's identical
        "omit if unchanged" rule for the Bash adapter's `updatedInput`).
      - Anything raises — filter registry construction, routing, or
        pipeline execution. Caught here (not just by __main__'s outer
        guard) so a single bad filter can't take down routing for every
        other Read call in the same process; mirrors
        `quor/adapters/dispatcher.py`'s own filter-layer try/except.

    Tracking (QB-007D): every branch that represents a genuine Read
    invocation — i.e. `file_path` is non-empty — calls `track_invocation()`
    exactly once before returning, mirroring how `dispatcher.py` tracks
    every Bash invocation it dispatches. The `command` column gets
    `"Read: {file_path}"` so Read rows are self-describing next to Bash
    rows in the same table; no schema change, no new storage. A `file_path`
    of "" is the one case treated as "nothing happened" and left untracked
    — the same way `dispatcher.run_dispatch([])` returns before dispatching
    or tracking anything for empty `args`.

    The passthrough/filter-name split mirrors `dispatcher.py`'s own
    `_lookup_filter`/`_apply_content_filter` split exactly:
      - no match, or a match outside `_READ_SUPPORTED_FILTER_NAMES`
        (including a `FilterRegistry` construction/lookup error) →
        `filter_name=None, was_passthrough=True` — nothing was applied.
      - a supported filter matched, whether or not applying it changed the
        content or raised (fail-open falls back to the original response) →
        `filter_name=<name>, was_passthrough=False` — a filter was
        genuinely attempted, same as dispatcher tracking `filter_config.name`
        even when `_apply_content_filter` itself caught an error.
    """
    tool_response = hook_input.tool_response
    file_path = hook_input.tool_input.file_path
    if not file_path:
        return None

    t0 = time.monotonic()
    command = f"Read: {file_path}"

    if not isinstance(tool_response, str):
        track_invocation(
            tracking,
            command=command,
            original="",
            filtered="",
            filter_name=None,
            was_passthrough=True,
            t0=t0,
        )
        return None

    try:
        registry = FilterRegistry(project_root=Path.cwd())
        filter_config = registry.find(file_path)
    except Exception as exc:  # noqa: BLE001 — fail-open: never let a filter error surface
        warnings.warn(f"[quor] Read filter error: {exc}", stacklevel=2)
        filter_config = None

    if filter_config is None or filter_config.name not in _READ_SUPPORTED_FILTER_NAMES:
        track_invocation(
            tracking,
            command=command,
            original=tool_response,
            filtered=tool_response,
            filter_name=None,
            was_passthrough=True,
            t0=t0,
        )
        return None

    try:
        rendered = registry.apply(filter_config, tool_response)
    except Exception as exc:  # noqa: BLE001 — fail-open: never let a filter error surface
        warnings.warn(f"[quor] Read filter error: {exc}", stacklevel=2)
        rendered = tool_response

    track_invocation(
        tracking,
        command=command,
        original=tool_response,
        filtered=rendered,
        filter_name=filter_config.name,
        was_passthrough=False,
        t0=t0,
    )

    if rendered == tool_response:
        return None
    return rendered
