"""Unit tests for QB-079's `file_intelligence.json` build-time helpers in
`quor/pipeline/repo_profile/intel.py`: `_primary_symbol_names()`,
`_classify_kind()`, and `_build_file_intelligence()`.

Also includes a parity test asserting `_build_file_intelligence()` and
`explorer.py::file_summary()` agree on `importance`/import counts for the
same synthetic repo — proving the `dashboard.importance_tiers()` extraction
(shared by both QB-078's `quor explore` and QB-079's build-time cache)
didn't silently diverge the two call sites.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from quor.pipeline.ast_summarize.symbol_model import Symbol
from quor.pipeline.repo_profile.explorer import ExplorerCache, file_summary
from quor.pipeline.repo_profile.graph import FileFacts
from quor.pipeline.repo_profile.graph_model import Edge, RepoDependencyGraph
from quor.pipeline.repo_profile.intel import (
    _build_file_intelligence,
    _classify_kind,
    _primary_symbol_names,
)
from quor.pipeline.repo_profile.intel_model import FileFingerprint, RepoIntelState
from quor.pipeline.repo_profile.model import DetectedItem, RepoProfile, RepoStatistics
from quor.pipeline.repo_profile.symbols_model import FileSymbols
from quor.pipeline.repo_profile.walk import WalkResult


def _profile(root: Path, *, configuration_files: list[DetectedItem] | None = None, lockfiles: list[str] | None = None) -> RepoProfile:
    return RepoProfile(
        root=root.as_posix(),
        configuration_files=configuration_files or [],
        lockfiles=lockfiles or [],
        statistics=RepoStatistics(total_files=0, total_directories=0, primary_language=None, git_commit_count=None),
    )


class TestPrimarySymbolNames:
    def test_none_input_returns_empty(self) -> None:
        assert _primary_symbol_names(None) == []

    def test_public_top_level_only_methods_excluded(self) -> None:
        fs = FileSymbols(
            path="a.py",
            language="python",
            symbols=[
                Symbol(name="Foo", kind="class", line=1, is_public=True),
                Symbol(name="_private", kind="function", line=5, is_public=False),
                Symbol(name="method", kind="method", line=10, is_public=True),
                Symbol(name="bar", kind="function", line=15, is_public=True),
            ],
        )
        assert _primary_symbol_names(fs) == ["Foo", "bar"]

    def test_declaration_line_order(self) -> None:
        fs = FileSymbols(
            path="a.py",
            language="python",
            symbols=[
                Symbol(name="second", kind="function", line=20, is_public=True),
                Symbol(name="first", kind="function", line=5, is_public=True),
            ],
        )
        assert _primary_symbol_names(fs) == ["first", "second"]

    def test_deduplicates_by_name(self) -> None:
        fs = FileSymbols(
            path="a.py",
            language="python",
            symbols=[
                Symbol(name="overload", kind="function", line=1, is_public=True),
                Symbol(name="overload", kind="function", line=5, is_public=True),
            ],
        )
        assert _primary_symbol_names(fs) == ["overload"]

    def test_capped_at_five(self) -> None:
        fs = FileSymbols(
            path="a.py",
            language="python",
            symbols=[Symbol(name=f"f{i}", kind="function", line=i, is_public=True) for i in range(10)],
        )
        assert _primary_symbol_names(fs) == ["f0", "f1", "f2", "f3", "f4"]


class TestClassifyKind:
    def test_test_directory_convention(self, tmp_path: Path) -> None:
        assert _classify_kind("tests/foo.py", tmp_path, configuration_paths=set(), scan_content=False) == "test"

    def test_test_name_prefix_convention(self, tmp_path: Path) -> None:
        assert _classify_kind("app/test_foo.py", tmp_path, configuration_paths=set(), scan_content=False) == "test"

    def test_test_name_suffix_convention(self, tmp_path: Path) -> None:
        assert _classify_kind("app/foo_test.py", tmp_path, configuration_paths=set(), scan_content=False) == "test"

    def test_test_dot_test_convention(self, tmp_path: Path) -> None:
        assert _classify_kind("src/foo.test.ts", tmp_path, configuration_paths=set(), scan_content=False) == "test"

    def test_generated_by_filename(self, tmp_path: Path) -> None:
        assert (
            _classify_kind("app/models_pb2.py", tmp_path, configuration_paths=set(), scan_content=False)
            == "generated"
        )

    def test_generated_by_bounded_content_scan(self, tmp_path: Path) -> None:
        (tmp_path / "widget.py").write_text("# Code generated by protoc. DO NOT EDIT.\nX = 1\n", encoding="utf-8")
        assert (
            _classify_kind("widget.py", tmp_path, configuration_paths=set(), scan_content=True) == "generated"
        )

    def test_content_scan_skipped_when_scan_content_false(self, tmp_path: Path) -> None:
        """Files with no `graph_facts` entry (not AST-covered) never get
        the bounded content scan — filename/directory evidence only."""
        (tmp_path / "widget.py").write_text("# DO NOT EDIT\nX = 1\n", encoding="utf-8")
        assert (
            _classify_kind("widget.py", tmp_path, configuration_paths=set(), scan_content=False) == "source"
        )

    def test_configuration_cross_reference(self, tmp_path: Path) -> None:
        assert (
            _classify_kind(
                "pyproject.toml", tmp_path, configuration_paths={"pyproject.toml"}, scan_content=False
            )
            == "configuration"
        )

    def test_default_is_source(self, tmp_path: Path) -> None:
        assert _classify_kind("app/service.py", tmp_path, configuration_paths=set(), scan_content=False) == "source"

    def test_vendor_directory_classified_as_generated(self, tmp_path: Path) -> None:
        assert (
            _classify_kind(
                "vendor/github.com/pkg/errors.go", tmp_path, configuration_paths=set(), scan_content=False
            )
            == "generated"
        )

    def test_minified_js_classified_as_generated(self, tmp_path: Path) -> None:
        assert (
            _classify_kind("static/jquery.min.js", tmp_path, configuration_paths=set(), scan_content=False)
            == "generated"
        )

    def test_minified_css_classified_as_generated(self, tmp_path: Path) -> None:
        assert (
            _classify_kind("static/app.min.css", tmp_path, configuration_paths=set(), scan_content=False)
            == "generated"
        )

    def test_test_takes_priority_over_configuration(self, tmp_path: Path) -> None:
        assert (
            _classify_kind(
                "tests/fixtures/config.json", tmp_path, configuration_paths={"tests/fixtures/config.json"}, scan_content=False
            )
            == "test"
        )


class TestBuildFileIntelligence:
    def _walk(self, root: Path, files: list[str]) -> WalkResult:
        for rel_path in files:
            path = root / rel_path
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists():
                path.write_text("", encoding="utf-8")
        return WalkResult(files=sorted(files), used_git=False)

    def test_import_and_imported_by_counts(self, tmp_path: Path) -> None:
        files = ["app/service.py", "app/util.py"]
        walk_result = self._walk(tmp_path, files)
        symbol_files = {
            "app/service.py": FileSymbols(
                path="app/service.py",
                language="python",
                symbols=[Symbol(name="run", kind="function", line=1, is_public=True)],
            ),
            "app/util.py": FileSymbols(path="app/util.py", language="python", symbols=[]),
        }
        graph_facts = {
            "app/service.py": FileFacts(language="python", symbol_counts=Counter({"run": 1}), relationships=[]),
            "app/util.py": FileFacts(language="python", symbol_counts=Counter(), relationships=[]),
        }
        edges = [
            Edge(
                kind="import",
                source_file="app/service.py",
                target_raw="app.util",
                line=1,
                target_file="app/util.py",
            )
        ]
        fingerprints = {p: FileFingerprint(size=0, mtime_ns=0, content_hash="x") for p in files}
        profile = _profile(tmp_path)

        entries = _build_file_intelligence(tmp_path, walk_result, symbol_files, graph_facts, edges, fingerprints, profile)

        assert entries["app/service.py"].imports == 1
        assert entries["app/service.py"].imported_by == 0
        assert entries["app/util.py"].imports == 0
        assert entries["app/util.py"].imported_by == 1
        assert entries["app/service.py"].top_symbols == ["run"]
        assert entries["app/service.py"].kind == "source"
        assert entries["app/service.py"].imported_files == ["app/util.py"]
        assert entries["app/util.py"].imported_files == []

    def test_imported_files_deduplicated_and_sorted_for_a_hub_file(self, tmp_path: Path) -> None:
        """QB-080: a file imported by many others (a "hub") must not be
        capped or silently dropped — `imported_files` is the *outgoing*
        direction only, so this exercises a hub file's own multiple
        outgoing imports, deduplicated (two edges to the same target
        collapse to one entry) and sorted, not just counted."""
        files = ["hub.py", "leaf_c.py", "leaf_a.py", "leaf_b.py"]
        walk_result = self._walk(tmp_path, files)
        fingerprints = {p: FileFingerprint(size=0, mtime_ns=0, content_hash="x") for p in files}
        profile = _profile(tmp_path)
        edges = [
            Edge(kind="import", source_file="hub.py", target_raw="c", line=1, target_file="leaf_c.py"),
            Edge(kind="import", source_file="hub.py", target_raw="a", line=2, target_file="leaf_a.py"),
            Edge(kind="import", source_file="hub.py", target_raw="b", line=3, target_file="leaf_b.py"),
            # A duplicate edge to the same target must not produce a duplicate entry.
            Edge(kind="import", source_file="hub.py", target_raw="a-again", line=4, target_file="leaf_a.py"),
        ]

        entries = _build_file_intelligence(tmp_path, walk_result, {}, {}, edges, fingerprints, profile)

        assert entries["hub.py"].imported_files == ["leaf_a.py", "leaf_b.py", "leaf_c.py"]

    def test_no_reverse_direction_is_persisted(self, tmp_path: Path) -> None:
        """QB-080's own explicit tradeoff: only the outgoing direction is
        ever stored on `FileIntelligenceEntry` — the target of an import
        edge gets no `imported_files` entry of its own from that edge (the
        reverse direction is derived in memory by `quor search`'s own
        `_build_reverse_import_index()`, never persisted a second time)."""
        files = ["a.py", "b.py"]
        walk_result = self._walk(tmp_path, files)
        fingerprints = {p: FileFingerprint(size=0, mtime_ns=0, content_hash="x") for p in files}
        profile = _profile(tmp_path)
        edges = [Edge(kind="import", source_file="a.py", target_raw="b", line=1, target_file="b.py")]

        entries = _build_file_intelligence(tmp_path, walk_result, {}, {}, edges, fingerprints, profile)

        assert entries["a.py"].imported_files == ["b.py"]
        assert entries["b.py"].imported_files == []

    def test_entry_point_detection(self, tmp_path: Path) -> None:
        files = ["main.py"]
        walk_result = self._walk(tmp_path, files)
        symbol_files = {
            "main.py": FileSymbols(
                path="main.py",
                language="python",
                symbols=[Symbol(name="main", kind="function", line=1, is_public=True, is_entry_point=True)],
            )
        }
        graph_facts = {"main.py": FileFacts(language="python", symbol_counts=Counter({"main": 1}), relationships=[])}
        fingerprints = {"main.py": FileFingerprint(size=0, mtime_ns=0, content_hash="x")}
        profile = _profile(tmp_path)

        entries = _build_file_intelligence(tmp_path, walk_result, symbol_files, graph_facts, [], fingerprints, profile)

        assert entries["main.py"].entry_point is True

    def test_file_with_no_ast_facts_gets_defaults(self, tmp_path: Path) -> None:
        files = ["README.md"]
        walk_result = self._walk(tmp_path, files)
        fingerprints = {"README.md": FileFingerprint(size=5, mtime_ns=100, content_hash="x")}
        profile = _profile(tmp_path)

        entries = _build_file_intelligence(tmp_path, walk_result, {}, {}, [], fingerprints, profile)

        entry = entries["README.md"]
        assert entry.top_symbols == []
        assert entry.imports == 0
        assert entry.imported_by == 0
        assert entry.imported_files == []
        assert entry.entry_point is False
        assert entry.language == "unknown"  # Markdown is excluded from languages.py's census
        assert entry.size == 5
        assert entry.mtime_ns == 100

    def test_configuration_file_from_profile_is_classified(self, tmp_path: Path) -> None:
        files = ["pyproject.toml"]
        walk_result = self._walk(tmp_path, files)
        fingerprints = {"pyproject.toml": FileFingerprint(size=0, mtime_ns=0, content_hash="x")}
        profile = _profile(
            tmp_path,
            configuration_files=[
                DetectedItem(name="pyproject", category="configuration", evidence=["pyproject.toml — project manifest"])
            ],
        )

        entries = _build_file_intelligence(tmp_path, walk_result, {}, {}, [], fingerprints, profile)

        assert entries["pyproject.toml"].kind == "configuration"


class TestImportanceParityWithExplorer:
    def test_build_file_intelligence_and_explorer_agree(self, tmp_path: Path) -> None:
        """Both `intel.py`'s build-time cache and `explorer.file_summary()`
        derive `importance`/import counts from the same
        `dashboard.importance_tiers()`/edge-filtering logic — this asserts
        they never silently diverge for the same repository state."""
        files = ["hub.py", "leaf_a.py", "leaf_b.py"]
        walk_result = WalkResult(files=sorted(files), used_git=False)
        for f in files:
            (tmp_path / f).write_text("", encoding="utf-8")

        symbol_files = {f: FileSymbols(path=f, language="python", symbols=[]) for f in files}
        graph_facts = {f: FileFacts(language="python", symbol_counts=Counter(), relationships=[]) for f in files}
        edges = [
            Edge(kind="import", source_file="hub.py", target_raw="leaf_a", line=1, target_file="leaf_a.py"),
            Edge(kind="import", source_file="hub.py", target_raw="leaf_b", line=2, target_file="leaf_b.py"),
        ]
        fingerprints = {f: FileFingerprint(size=0, mtime_ns=0, content_hash="x") for f in files}
        profile = _profile(tmp_path)

        built = _build_file_intelligence(tmp_path, walk_result, symbol_files, graph_facts, edges, fingerprints, profile)

        graph = RepoDependencyGraph(root=tmp_path.as_posix(), edges=edges, total_edges=len(edges), resolved_edges=len(edges))
        state = RepoIntelState(
            schema_version=1,
            quor_version="0.0.0",
            repo_root=tmp_path.as_posix(),
            git_head=None,
            file_count=len(files),
            last_scan_timestamp="2026-01-01T00:00:00+00:00",
            last_completed_build="2026-01-01T00:00:00+00:00",
            fingerprints=fingerprints,
        )
        cache = ExplorerCache(
            root=tmp_path,
            state=state,
            profile=profile,
            symbol_files=symbol_files,
            graph_facts=graph_facts,
            graph=graph,
            cache_status="fresh",
        )

        for f in files:
            explorer_summary = file_summary(cache, f)
            assert explorer_summary is not None
            assert built[f].importance == explorer_summary.importance
            assert built[f].imports == explorer_summary.import_count
